name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install latest nightly Rust compiler
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Download npm dependencies
        working-directory: feather_grammar
        run: npm ci

      - name: Build tree-sitter grammar
        working-directory: feather_grammar
        run: npm run generate

      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt --check --workspace --verbose

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy --workspace --verbose

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build --workspace --verbose

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test --workspace --verbose
